### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by moonglazer** [19-1-skku-oss/2019-1-OSS-E1#24]
Heap Sort를 이미 만들어진 binary tree안에 만들려고 합니다. 그런데 그러면 binary tree와 Heap sort가 동시에 한 개의 파일안에 있는데 그러면 어떤 폴더 안에 넣어야 합니까?

**Comment by Mysigyeong** [comment]
힙소트면 정렬이니 SortingEnv에 넣는것이 바람직해보입니다.

**Comment by moonglazer** [comment]
그러면 SortingEnv에 넣겠습니다.
