### ISSUE TITLE
heap_sort, quick_sort 관련 이슈

### ISSUE THREAD

**Issue by Mysigyeong** [19-1-skku-oss/2019-1-OSS-E1#28]
정렬 알고리즘을 이용하는 예시를 main함수에 넣어주시면 더 좋을 것 같습니다.
quick_sort는 main함수에서 예시 array를 만들기만 하고 정렬하는 모습을 보여주지 않고있고, heap_sort는 main함수가 없네요.
이 두 부분만 추가를 해주셨으면 합니다.

**Comment by moonglazer** [comment]
heap_sort는 heap을 이용해서 priority queue를 만들고 priority queue에서 heap sort를 이용한 정렬을 보여줄거라서 나중에 만들 계획입니다. 그리고 quick sort는 만들어서 올리겠습니다.
