### ISSUE TITLE
자료정리

### ISSUE THREAD

**Issue by moonglazer** [19-1-skku-oss/2019-1-OSS-E1#30]
지금 저장소에 필요없는 자료랑 정리되지 않은 자료가 많아서 보기가 안좋은거 같습니다. 한번 정리해서 강제로 push 해야할거 같습니다. 그래서 내일 제가 pull request를 다 받고 정리할까 하는데 어떻습니까?

**Comment by Mysigyeong** [comment]
지금 자료 정리를 하면 pull request하는데 애로사항이 생길 것 같아서 실습시간에 모여서 의논을 하고 정리를 하는 것이 더 바람직해 보입니다.
